version: "3.7"

services:
  envoy:
    container_name: envoy
    image: envoyproxy/envoy:distroless-v1.28-latest
    command: -c /etc/envoy/envoy.yaml
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "8080:80"
